name: Release
on:
    push:  
      tags:
        - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Dump Tag
        run: echo ${GITHUB_REF}
      - name: Dump Tag
        run: echo ${GITHUB_REF:10}
  
  compress:
    name: Compress
    runs-on: windows-latest
    steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2
        - name: Compress
          run: 7z a example.zip action-a README.md
        - uses: actions/upload-artifact@v1
          with:
            name: releases
            path: example.zip
        - name: Compress 2
          run: 7z a example2.zip README.md
        - uses: actions/upload-artifact@v1
          with:
            name: releases
            path: example2.zip
    
